[package]
name = "duststorm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
voronoice = "0.2.0"

[[bin]]
name = "voronoi"
path = "src/voronoi.rs"
